//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute_Inflow
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<int> Dept_Market { get; set; }
        public string Region { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public Nullable<int> Brands { get; set; }
        public Nullable<int> Prints { get; set; }
        public Nullable<int> Materials { get; set; }
        public Nullable<int> Colors_Size { get; set; }
        public Nullable<int> ReadyToPost { get; set; }
        public Nullable<int> Live { get; set; }
    }
}
