//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        public int user_id { get; set; }
        public string employee_name { get; set; }
        public string employee_id { get; set; }
        public int role_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public bool is_active { get; set; }
        public bool is_delete { get; set; }
        public Nullable<int> created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
